### ISSUE TITLE
Usernames over 30 characters cause the database to crash

### ISSUE THREAD

**Issue by C-Bouthoorn** [eJourn-al/eJournal#472]
**Describe the bug**
If a username with more than 30 characters is entered, the database crashes.

**To Reproduce**

0. `sudo make install && sudo make deploy && sudo make serve`
1. Go to `localhost/Register`
2. Fill in for username `a reaaaaaaaaaaaaaaaaaaally long uuuuuuuuuusernaaaaaaaame`

**Expected behaviour**
The database not to crash

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: `develop` branch

**Stacktrace:**

```
ERROR:django.request:Internal Server Error: /users/, referer: http://localhost/Register
 Traceback (most recent call last):, referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute, referer: http://localhost/Register
     return self.cursor.execute(sql, params), referer: http://localhost/Register
 psycopg2.DataError: value too long for type character varying(30), referer: http://localhost/Register
 , referer: http://localhost/Register
 , referer: http://localhost/Register
 The above exception was the direct cause of the following exception:, referer: http://localhost/Register
 , referer: http://localhost/Register
 Traceback (most recent call last):, referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner, referer: http://localhost/Register
     response = get_response(request), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response, referer: http://localhost/Register
     response = self.process_exception_by_middleware(e, request), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response, referer: http://localhost/Register
     response = wrapped_callback(request, *callback_args, **callback_kwargs), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view, referer: http://localhost/Register
     return view_func(*args, **kwargs), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view, referer: http://localhost/Register
     return self.dispatch(request, *args, **kwargs), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch, referer: http://localhost/Register
     response = self.handle_exception(exc), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception, referer: http://localhost/Register
     self.raise_uncaught_exception(exc), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch, referer: http://localhost/Register
     response = handler(request, *args, **kwargs), referer: http://localhost/Register
   File "/var/www/ejournal//django/VLE/views/user.py", line 134, in create, referer: http://localhost/Register
     verified_email=True if lti_id else False), referer: http://localhost/Register
   File "/var/www/ejournal//django/VLE/factory.py", line 44, in make_user, referer: http://localhost/Register
     user.save(), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save, referer: http://localhost/Register
     super().save(*args, **kwargs), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save, referer: http://localhost/Register
     force_update=force_update, update_fields=update_fields), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base, referer: http://localhost/Register
     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table, referer: http://localhost/Register
     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert, referer: http://localhost/Register
     using=using, raw=raw), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method, referer: http://localhost/Register
     return getattr(self.get_queryset(), name)(*args, **kwargs), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert, referer: http://localhost/Register
     return query.get_compiler(using=using).execute_sql(return_id), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql, referer: http://localhost/Register
     cursor.execute(sql, params), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute, referer: http://localhost/Register
     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers, referer: http://localhost/Register
     return executor(sql, params, many, context), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute, referer: http://localhost/Register
     return self.cursor.execute(sql, params), referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__, referer: http://localhost/Register
     raise dj_exc_value.with_traceback(traceback) from exc_value, referer: http://localhost/Register
   File "/var/www/ejournal/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute, referer: http://localhost/Register
     return self.cursor.execute(sql, params), referer: http://localhost/Register
 django.db.utils.DataError: value too long for type character varying(30), referer: http://localhost/Register
 , referer: http://localhost/Register
```

**Comment by mjvkeulen** [comment]
Thank you for the input!

Not sure if this qualifies as a bug however, for our current deploy usernames are restricted to student numbers which are max 11 chars. The django default AbstractUser class username field is a charfield with max 30 characters. Easily overwritten for a different deploy if so desired.

I agree more defined error handling will be useful for full custom registration later down the road!

**Comment by Rickyboy320** [comment]
If it's possible on the develop through /Register, it is definitely a bug.
At the very minimum it should not throw a 500 error.
